### ISSUE TITLE
AttributeError: 'function' object has no attribute 'config'

### ISSUE THREAD

**Issue by jessedev** [Snaipe/Tequila#11]
Starting multiple instances is giving this bug:

```
root@server:/home/minecraft/servers/demo/config# tequila start demo#1-5
Traceback (most recent call last):
  File "/usr/local/bin/tequila", line 7, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/.pip/src/tequila./bin/tequila", line 5, in <module>
    Tequila().main()
  File "/usr/bin/src/tequila./tequila/__init__.py", line 55, in main
    baker.run()
  File "/usr/lib/python3.4/site-packages/baker.py", line 823, in run
    value = self.apply(*self.parse(argv), instance=instance)
  File "/usr/lib/python3.4/site-packages/baker.py", line 801, in apply
    return cmd.fn(*newargs, **newkwargs)
  File "/usr/bin/src/tequila./tequila/command.py", line 136, in cmd_start
    if not serv.config.are_instances_enabled():
```

Using python 3.4. This is my config btw:

```
[general]
user: minecraft
server: org.spigotmc:spigot:1.7.10-R0.1-SNAPSHOT
stop-command: stop
wrapper-type: screen

[directories]
plugins: plugins
worlds: worlds

[multiple-instances]
enabled: true
startup-policy: copy
binding-policy: fixed
port-range: 3000, 3005

[options]
jvm: jvm.opts
application: application.opts

[version-control]
enabled: false
config-files: *.yml, *.properties
data-files: *.dat, *.dat_old, *.dat_mcr, *.mca, *.json

[repositories]
bukkit: http://repo.bukkit.org/content/groups/public/

# Below are popular plugin/server repositories, you may uncomment the lines you need
spigot: http://repo.md-5.net/content/groups/public/
#sk89q: http://maven.sk89q.com/repo/
#kitteh: http://repo.kitteh.org/content/groups/public/
#comphenix: http://repo.comphenix.net/content/repositories/public/

# blackdog is a local webservice that maps bukkitdev plugins to a maven repository structure
# for more information, see http://github.com/Snaipe/BlackDog.git
#blackdog: http://localhost:8140/

[plugins]
#WorldEdit: com.sk89q:worldedit:6.0.0-SNAPSHOT
#Vault: net.milkbowl.vault:Vault:1.2.16
```

**Comment by Snaipe** [comment]
(This is exactly why tequila need tests. Goddammit)

**Comment by jessedev** [comment]
Thanks! :+1:
