### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Chunkr-** [Snaipe/Tequila#2]
tequila 
Traceback (most recent call last):
  File "/usr/local/bin/tequila", line 10, in <module>
    execfile(**file**)
  File "/root/src/tequila/bin/tequila", line 2, in <module>
    from tequila import Tequila
  File "/root/src/tequila/tequila/**init**.py", line 24, in <module>
    from tequila.server import Server
  File "/root/src/tequila/tequila/server.py", line 102
    raise ServerConfigurationNotFoundException(self) from e
                                                        ^
SyntaxError: invalid syntax

**Comment by Snaipe** [comment]
@DatChunkr 
You are using an older version of python, Tequila uses python 3.4 (though it should work for all versions after 3.0).
Install a more recent version of python, uninstall tequila (and maybe blackdog) from python 2.x, and reinstall it using pip for python 3.x. This should fix your issue.

I am going to set the requirements on pypi.org for python 3.x.
